---

- name: Installation de Apache2 sur le serveur
  hosts: apache2
  remote_user: root
  vars:
    domains:
      - www.hei.school
      - front.hei.school
      - back.hei.School
      - api.hei.school

  tasks:
    - name: Installing all the required tools
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: latest
      with_items:
        - apache2

    - name: Creating the directories for the HTML files
      command: mkdir /var/www/{{ item }}
      loop: "{{ domains }}"
    
<<<<<<< HEAD
    - name: Creating the HTML files of the docs
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: /var/www/{{ item }}/index.html
      loop: "{{ domains }}"

    - name: Creating the VirtualHost configuration file
      ansible.builtin.template:
        src: templates/domain.conf.j2
        dest: /etc/apache2/sites-available/{{ item }}.conf
=======
    - name: Creating the HTML files of each domain name
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: /var/www/{{ item }}/index.html
>>>>>>> 5228bce449735aaf27500a03fc29898963fb2d0c
      loop: "{{ domains }}"
...
