---

- name: Installation de Apache2 sur le serveur
  hosts: apache2
  remote_user: root

  tasks:
    - name: Install required tools
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - apache2
        - sudo
        - git        

...
